/**
 * @file test_runner.c
 * @brief Unity entry point aggregating every test_*_reg.c suite in this
 *        directory into one run_tests binary.
 *
 * Each test_<peripheral>_reg.c file owns only its test functions, with
 * no main() and no setUp/tearDown, since Unity requires exactly one
 * definition of each per binary. This file supplies both, and invokes
 * RUN_TEST() for every test function via an extern declaration rather
 * than an #include, so each test file compiles, and can be reasoned
 * about, as an independent translation unit.
 */
#include "unity.h"

void setUp(void) {}
void tearDown(void) {}

extern void test_gpio_base_addresses_are_evenly_spaced(void);
extern void test_gpio_register_block_size(void);
extern void test_gpio_driver_init_rejects_invalid_mode(void);
extern void test_gpio_driver_init_rejects_invalid_otype(void);
extern void test_gpio_driver_init_rejects_invalid_ospeed(void);
extern void test_gpio_driver_init_rejects_reserved_pupd(void);
extern void test_gpio_driver_init_sets_fields_for_specified_pin_only(void);
extern void test_gpio_driver_init_does_not_touch_afr(void);
extern void test_gpio_driver_deinit_clears_fields_for_specified_pin_only(void);
extern void test_gpio_driver_deinit_clears_afrl_for_low_pins(void);
extern void test_gpio_driver_deinit_clears_afrh_for_high_pins(void);
extern void test_gpio_driver_set_alternate_function_rejects_invalid_af(void);
extern void test_gpio_driver_set_alternate_function_writes_afrl_for_low_pins(void);
extern void test_gpio_driver_set_alternate_function_writes_afrh_for_high_pins(void);
extern void test_gpio_driver_write_pin_set_uses_bsrr_set_half(void);
extern void test_gpio_driver_write_pin_reset_uses_bsrr_reset_half(void);
extern void test_gpio_driver_read_pin_reports_set_when_idr_bit_high(void);
extern void test_gpio_driver_read_pin_reports_reset_when_idr_bit_low(void);
extern void test_gpio_driver_toggle_pin_drives_high_when_odr_bit_low(void);
extern void test_gpio_driver_toggle_pin_drives_low_when_odr_bit_high(void);
extern void test_rcc_ahb1enr_gpio_enable_bits_do_not_overlap(void);
extern void test_rcc_pwren_and_syscfgen_bit_positions(void);
extern void test_rcc_cfgr_sysclk_values_are_distinct_and_in_range(void);
extern void test_rcc_cfgr_hpre_values_are_distinct_and_in_range(void);
extern void test_rcc_cfgr_ppre_values_are_distinct_and_in_range(void);
extern void test_rcc_pllcfgr_pllp_values_are_distinct_and_in_range(void);
extern void test_rcc_driver_gpio_clock_enable_maps_every_port_to_its_documented_bit(void);
extern void test_rcc_driver_gpio_clock_disable_maps_every_port_to_its_documented_bit(void);
extern void test_rcc_driver_gpio_clock_enable_rejects_unrecognized_port(void);
extern void test_rcc_driver_gpio_clock_disable_rejects_unrecognized_port(void);
extern void test_rcc_driver_gpio_clock_enable_preserves_other_bits(void);
extern void test_rcc_driver_gpio_clock_disable_preserves_other_bits(void);
extern void test_rcc_driver_usart2_clock_enable_sets_bit_only(void);
extern void test_rcc_driver_usart2_clock_disable_clears_bit_only(void);
extern void test_rcc_driver_syscfg_clock_enable_sets_bit_only(void);
extern void test_rcc_driver_syscfg_clock_disable_clears_bit_only(void);
extern void test_rcc_driver_pwr_clock_enable_sets_bit_only(void);
extern void test_rcc_driver_pwr_clock_disable_clears_bit_only(void);
extern void test_rcc_driver_hsi_enable_reports_ok_when_ready(void);
extern void test_rcc_driver_hsi_enable_times_out_when_hsirdy_never_sets(void);
extern void test_rcc_driver_hsi_disable_clears_hsion_when_not_active_source(void);
extern void test_rcc_driver_hsi_disable_rejects_when_active_source(void);
extern void test_rcc_driver_hse_enable_rejects_invalid_bypass(void);
extern void test_rcc_driver_hse_enable_rejects_when_already_on(void);
extern void test_rcc_driver_hse_enable_bypass_mode_sets_hsebyp_and_hseon(void);
extern void test_rcc_driver_hse_enable_crystal_mode_leaves_hsebyp_clear(void);
extern void test_rcc_driver_hse_enable_times_out_when_hserdy_never_sets(void);
extern void test_rcc_driver_hse_disable_clears_hseon_when_not_active_source(void);
extern void test_rcc_driver_hse_disable_rejects_when_active_source(void);
extern void test_rcc_driver_pll_config_rejects_invalid_source(void);
extern void test_rcc_driver_pll_config_rejects_m_out_of_range(void);
extern void test_rcc_driver_pll_config_rejects_n_out_of_range(void);
extern void test_rcc_driver_pll_config_rejects_p_out_of_range(void);
extern void test_rcc_driver_pll_config_rejects_when_already_on(void);
extern void test_rcc_driver_pll_config_writes_fields_and_preserves_pllq(void);
extern void test_rcc_driver_pll_enable_reports_ok_when_ready(void);
extern void test_rcc_driver_pll_enable_times_out_when_pllrdy_never_sets(void);
extern void test_rcc_driver_pll_disable_clears_pllon_when_not_active_source(void);
extern void test_rcc_driver_pll_disable_rejects_when_active_source(void);
extern void test_rcc_driver_bus_prescaler_config_rejects_invalid_hpre(void);
extern void test_rcc_driver_bus_prescaler_config_rejects_invalid_ppre1(void);
extern void test_rcc_driver_bus_prescaler_config_rejects_invalid_ppre2(void);
extern void test_rcc_driver_bus_prescaler_config_writes_all_three_fields(void);
extern void test_rcc_driver_bus_prescaler_config_accepts_every_documented_hpre(void);
extern void test_rcc_driver_bus_prescaler_config_accepts_every_documented_ppre(void);
extern void test_rcc_driver_sysclk_switch_rejects_invalid_source(void);
extern void test_rcc_driver_sysclk_switch_propagates_flash_invalid_param(void);
extern void test_rcc_driver_sysclk_switch_reports_not_initialized_when_source_not_ready(void);
extern void test_rcc_driver_sysclk_switch_switches_and_reports_ok(void);
extern void test_rcc_driver_sysclk_switch_to_hsi_switches_and_reports_ok(void);
extern void test_rcc_driver_sysclk_switch_to_hse_switches_and_reports_ok(void);
extern void test_rcc_driver_sysclk_switch_times_out_when_sws_never_matches(void);
extern void test_flash_driver_set_latency_rejects_invalid_latency(void);
extern void test_flash_driver_set_latency_accepts_full_field_width(void);
extern void test_flash_driver_set_latency_touches_only_latency_field(void);
extern void test_flash_driver_set_latency_read_back_accepts_every_encoding(void);
extern void test_pwr_driver_set_voltage_scale_rejects_reserved_zero(void);
extern void test_pwr_driver_set_voltage_scale_rejects_out_of_range(void);
extern void test_pwr_driver_set_voltage_scale_writes_each_documented_scale(void);
extern void test_pwr_driver_set_voltage_scale_touches_only_vos_field(void);
extern void test_pwr_driver_set_voltage_scale_does_not_poll_vosrdy(void);
extern void test_pwr_driver_wait_voltage_scale_ready_reports_ok_when_vosrdy_set(void);
extern void test_pwr_driver_wait_voltage_scale_ready_times_out_when_vosrdy_never_sets(void);
extern void test_pwr_driver_wait_voltage_scale_ready_does_not_write_cr(void);
extern void test_uart_driver_init_computes_brr_for_45mhz_115200(void);
extern void test_uart_driver_init_computes_brr_for_16mhz_9600(void);
extern void test_uart_driver_init_computes_brr_with_fraction_carry(void);
extern void test_uart_driver_init_rejects_zero_pclk(void);
extern void test_uart_driver_init_rejects_zero_baud(void);
extern void test_uart_driver_init_rejects_baud_too_low_for_pclk(void);
extern void test_uart_driver_init_rejects_baud_too_high_for_pclk(void);
extern void test_uart_driver_init_accepts_zero_mantissa_with_nonzero_fraction(void);
extern void test_uart_driver_init_rejects_invalid_stop_bits(void);
extern void test_uart_driver_init_accepts_every_documented_stop_bits(void);
extern void test_uart_driver_init_rejects_invalid_parity_enable(void);
extern void test_uart_driver_init_rejects_invalid_parity_select(void);
extern void test_uart_driver_init_rejects_invalid_direction(void);
extern void test_uart_driver_init_sets_fields_and_preserves_other_bits(void);
extern void test_uart_driver_init_clears_preexisting_m_bit(void);
extern void test_uart_driver_init_defaults_clear_parity_and_re(void);
extern void test_uart_driver_init_reconfigures_an_already_enabled_instance(void);
extern void test_uart_driver_deinit_resets_all_registers(void);
extern void test_uart_driver_transmit_byte_writes_dr_when_txe_ready(void);
extern void test_uart_driver_transmit_byte_times_out_when_txe_never_sets(void);
extern void test_uart_driver_transmit_sends_every_byte_in_order(void);
extern void test_uart_driver_transmit_zero_length_reports_ok(void);
extern void test_uart_driver_transmit_propagates_timeout(void);
extern void test_uart_driver_transmit_times_out_when_tc_never_sets(void);
extern void test_uart_driver_flush_reports_ok_when_tc_set(void);
extern void test_uart_driver_flush_times_out_when_tc_never_sets(void);
extern void test_uart_driver_flush_does_not_write_dr(void);
extern void test_uart_driver_receive_byte_reads_dr_when_no_fault(void);
extern void test_uart_driver_receive_byte_times_out_when_rxne_never_sets(void);
extern void test_uart_driver_receive_byte_reports_fault_but_still_reads_dr(void);
extern void test_uart_driver_receive_byte_reports_fault_for_ne_fe_pe(void);
extern void test_uart_driver_receive_reads_every_byte_in_order(void);
extern void test_uart_driver_receive_zero_length_reports_ok(void);
extern void test_uart_driver_receive_propagates_timeout(void);
extern void test_systick_base_address(void);
extern void test_uart_register_block_size(void);
extern void test_usart_sr_flag_bits_do_not_overlap(void);
extern void test_usart2_base_address(void);
extern void test_nvic_register_block_size_and_offsets(void);
extern void test_scb_register_block_size_and_offset(void);
extern void test_fpu_register_block_size(void);
extern void test_scb_cfsr_fault_status_byte_fields_do_not_overlap(void);
extern void test_mpu_register_block_size(void);
extern void test_mpu_rasr_ap_values_are_distinct_and_in_range(void);
extern void test_flash_register_block_size(void);
extern void test_pwr_register_block_size(void);
extern void test_pwr_cr_vos_scale_values_are_distinct(void);
extern void test_iwdg_register_block_size(void);
extern void test_iwdg_key_values_are_distinct(void);
extern void test_wwdg_register_block_size(void);
extern void test_exti_register_block_size(void);
extern void test_exti_line_numbers_are_distinct_and_above_gpio_range(void);
extern void test_syscfg_register_block_size(void);
extern void test_syscfg_exticr_port_values_are_distinct_and_in_range(void);

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_gpio_base_addresses_are_evenly_spaced);
    RUN_TEST(test_gpio_register_block_size);
    RUN_TEST(test_gpio_driver_init_rejects_invalid_mode);
    RUN_TEST(test_gpio_driver_init_rejects_invalid_otype);
    RUN_TEST(test_gpio_driver_init_rejects_invalid_ospeed);
    RUN_TEST(test_gpio_driver_init_rejects_reserved_pupd);
    RUN_TEST(test_gpio_driver_init_sets_fields_for_specified_pin_only);
    RUN_TEST(test_gpio_driver_init_does_not_touch_afr);
    RUN_TEST(test_gpio_driver_deinit_clears_fields_for_specified_pin_only);
    RUN_TEST(test_gpio_driver_deinit_clears_afrl_for_low_pins);
    RUN_TEST(test_gpio_driver_deinit_clears_afrh_for_high_pins);
    RUN_TEST(test_gpio_driver_set_alternate_function_rejects_invalid_af);
    RUN_TEST(test_gpio_driver_set_alternate_function_writes_afrl_for_low_pins);
    RUN_TEST(test_gpio_driver_set_alternate_function_writes_afrh_for_high_pins);
    RUN_TEST(test_gpio_driver_write_pin_set_uses_bsrr_set_half);
    RUN_TEST(test_gpio_driver_write_pin_reset_uses_bsrr_reset_half);
    RUN_TEST(test_gpio_driver_read_pin_reports_set_when_idr_bit_high);
    RUN_TEST(test_gpio_driver_read_pin_reports_reset_when_idr_bit_low);
    RUN_TEST(test_gpio_driver_toggle_pin_drives_high_when_odr_bit_low);
    RUN_TEST(test_gpio_driver_toggle_pin_drives_low_when_odr_bit_high);
    RUN_TEST(test_rcc_ahb1enr_gpio_enable_bits_do_not_overlap);
    RUN_TEST(test_rcc_pwren_and_syscfgen_bit_positions);
    RUN_TEST(test_rcc_cfgr_sysclk_values_are_distinct_and_in_range);
    RUN_TEST(test_rcc_cfgr_hpre_values_are_distinct_and_in_range);
    RUN_TEST(test_rcc_cfgr_ppre_values_are_distinct_and_in_range);
    RUN_TEST(test_rcc_pllcfgr_pllp_values_are_distinct_and_in_range);
    RUN_TEST(test_rcc_driver_gpio_clock_enable_maps_every_port_to_its_documented_bit);
    RUN_TEST(test_rcc_driver_gpio_clock_disable_maps_every_port_to_its_documented_bit);
    RUN_TEST(test_rcc_driver_gpio_clock_enable_rejects_unrecognized_port);
    RUN_TEST(test_rcc_driver_gpio_clock_disable_rejects_unrecognized_port);
    RUN_TEST(test_rcc_driver_gpio_clock_enable_preserves_other_bits);
    RUN_TEST(test_rcc_driver_gpio_clock_disable_preserves_other_bits);
    RUN_TEST(test_rcc_driver_usart2_clock_enable_sets_bit_only);
    RUN_TEST(test_rcc_driver_usart2_clock_disable_clears_bit_only);
    RUN_TEST(test_rcc_driver_syscfg_clock_enable_sets_bit_only);
    RUN_TEST(test_rcc_driver_syscfg_clock_disable_clears_bit_only);
    RUN_TEST(test_rcc_driver_pwr_clock_enable_sets_bit_only);
    RUN_TEST(test_rcc_driver_pwr_clock_disable_clears_bit_only);
    RUN_TEST(test_rcc_driver_hsi_enable_reports_ok_when_ready);
    RUN_TEST(test_rcc_driver_hsi_enable_times_out_when_hsirdy_never_sets);
    RUN_TEST(test_rcc_driver_hsi_disable_clears_hsion_when_not_active_source);
    RUN_TEST(test_rcc_driver_hsi_disable_rejects_when_active_source);
    RUN_TEST(test_rcc_driver_hse_enable_rejects_invalid_bypass);
    RUN_TEST(test_rcc_driver_hse_enable_rejects_when_already_on);
    RUN_TEST(test_rcc_driver_hse_enable_bypass_mode_sets_hsebyp_and_hseon);
    RUN_TEST(test_rcc_driver_hse_enable_crystal_mode_leaves_hsebyp_clear);
    RUN_TEST(test_rcc_driver_hse_enable_times_out_when_hserdy_never_sets);
    RUN_TEST(test_rcc_driver_hse_disable_clears_hseon_when_not_active_source);
    RUN_TEST(test_rcc_driver_hse_disable_rejects_when_active_source);
    RUN_TEST(test_rcc_driver_pll_config_rejects_invalid_source);
    RUN_TEST(test_rcc_driver_pll_config_rejects_m_out_of_range);
    RUN_TEST(test_rcc_driver_pll_config_rejects_n_out_of_range);
    RUN_TEST(test_rcc_driver_pll_config_rejects_p_out_of_range);
    RUN_TEST(test_rcc_driver_pll_config_rejects_when_already_on);
    RUN_TEST(test_rcc_driver_pll_config_writes_fields_and_preserves_pllq);
    RUN_TEST(test_rcc_driver_pll_enable_reports_ok_when_ready);
    RUN_TEST(test_rcc_driver_pll_enable_times_out_when_pllrdy_never_sets);
    RUN_TEST(test_rcc_driver_pll_disable_clears_pllon_when_not_active_source);
    RUN_TEST(test_rcc_driver_pll_disable_rejects_when_active_source);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_rejects_invalid_hpre);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_rejects_invalid_ppre1);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_rejects_invalid_ppre2);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_writes_all_three_fields);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_accepts_every_documented_hpre);
    RUN_TEST(test_rcc_driver_bus_prescaler_config_accepts_every_documented_ppre);
    RUN_TEST(test_rcc_driver_sysclk_switch_rejects_invalid_source);
    RUN_TEST(test_rcc_driver_sysclk_switch_propagates_flash_invalid_param);
    RUN_TEST(test_rcc_driver_sysclk_switch_reports_not_initialized_when_source_not_ready);
    RUN_TEST(test_rcc_driver_sysclk_switch_switches_and_reports_ok);
    RUN_TEST(test_rcc_driver_sysclk_switch_to_hsi_switches_and_reports_ok);
    RUN_TEST(test_rcc_driver_sysclk_switch_to_hse_switches_and_reports_ok);
    RUN_TEST(test_rcc_driver_sysclk_switch_times_out_when_sws_never_matches);
    RUN_TEST(test_flash_driver_set_latency_rejects_invalid_latency);
    RUN_TEST(test_flash_driver_set_latency_accepts_full_field_width);
    RUN_TEST(test_flash_driver_set_latency_touches_only_latency_field);
    RUN_TEST(test_flash_driver_set_latency_read_back_accepts_every_encoding);
    RUN_TEST(test_pwr_driver_set_voltage_scale_rejects_reserved_zero);
    RUN_TEST(test_pwr_driver_set_voltage_scale_rejects_out_of_range);
    RUN_TEST(test_pwr_driver_set_voltage_scale_writes_each_documented_scale);
    RUN_TEST(test_pwr_driver_set_voltage_scale_touches_only_vos_field);
    RUN_TEST(test_pwr_driver_set_voltage_scale_does_not_poll_vosrdy);
    RUN_TEST(test_pwr_driver_wait_voltage_scale_ready_reports_ok_when_vosrdy_set);
    RUN_TEST(test_pwr_driver_wait_voltage_scale_ready_times_out_when_vosrdy_never_sets);
    RUN_TEST(test_pwr_driver_wait_voltage_scale_ready_does_not_write_cr);
    RUN_TEST(test_uart_driver_init_computes_brr_for_45mhz_115200);
    RUN_TEST(test_uart_driver_init_computes_brr_for_16mhz_9600);
    RUN_TEST(test_uart_driver_init_computes_brr_with_fraction_carry);
    RUN_TEST(test_uart_driver_init_rejects_zero_pclk);
    RUN_TEST(test_uart_driver_init_rejects_zero_baud);
    RUN_TEST(test_uart_driver_init_rejects_baud_too_low_for_pclk);
    RUN_TEST(test_uart_driver_init_rejects_baud_too_high_for_pclk);
    RUN_TEST(test_uart_driver_init_accepts_zero_mantissa_with_nonzero_fraction);
    RUN_TEST(test_uart_driver_init_rejects_invalid_stop_bits);
    RUN_TEST(test_uart_driver_init_accepts_every_documented_stop_bits);
    RUN_TEST(test_uart_driver_init_rejects_invalid_parity_enable);
    RUN_TEST(test_uart_driver_init_rejects_invalid_parity_select);
    RUN_TEST(test_uart_driver_init_rejects_invalid_direction);
    RUN_TEST(test_uart_driver_init_sets_fields_and_preserves_other_bits);
    RUN_TEST(test_uart_driver_init_clears_preexisting_m_bit);
    RUN_TEST(test_uart_driver_init_defaults_clear_parity_and_re);
    RUN_TEST(test_uart_driver_init_reconfigures_an_already_enabled_instance);
    RUN_TEST(test_uart_driver_deinit_resets_all_registers);
    RUN_TEST(test_uart_driver_transmit_byte_writes_dr_when_txe_ready);
    RUN_TEST(test_uart_driver_transmit_byte_times_out_when_txe_never_sets);
    RUN_TEST(test_uart_driver_transmit_sends_every_byte_in_order);
    RUN_TEST(test_uart_driver_transmit_zero_length_reports_ok);
    RUN_TEST(test_uart_driver_transmit_propagates_timeout);
    RUN_TEST(test_uart_driver_transmit_times_out_when_tc_never_sets);
    RUN_TEST(test_uart_driver_flush_reports_ok_when_tc_set);
    RUN_TEST(test_uart_driver_flush_times_out_when_tc_never_sets);
    RUN_TEST(test_uart_driver_flush_does_not_write_dr);
    RUN_TEST(test_uart_driver_receive_byte_reads_dr_when_no_fault);
    RUN_TEST(test_uart_driver_receive_byte_times_out_when_rxne_never_sets);
    RUN_TEST(test_uart_driver_receive_byte_reports_fault_but_still_reads_dr);
    RUN_TEST(test_uart_driver_receive_byte_reports_fault_for_ne_fe_pe);
    RUN_TEST(test_uart_driver_receive_reads_every_byte_in_order);
    RUN_TEST(test_uart_driver_receive_zero_length_reports_ok);
    RUN_TEST(test_uart_driver_receive_propagates_timeout);
    RUN_TEST(test_systick_base_address);
    RUN_TEST(test_uart_register_block_size);
    RUN_TEST(test_usart_sr_flag_bits_do_not_overlap);
    RUN_TEST(test_usart2_base_address);
    RUN_TEST(test_nvic_register_block_size_and_offsets);
    RUN_TEST(test_scb_register_block_size_and_offset);
    RUN_TEST(test_fpu_register_block_size);
    RUN_TEST(test_scb_cfsr_fault_status_byte_fields_do_not_overlap);
    RUN_TEST(test_mpu_register_block_size);
    RUN_TEST(test_mpu_rasr_ap_values_are_distinct_and_in_range);
    RUN_TEST(test_flash_register_block_size);
    RUN_TEST(test_pwr_register_block_size);
    RUN_TEST(test_pwr_cr_vos_scale_values_are_distinct);
    RUN_TEST(test_iwdg_register_block_size);
    RUN_TEST(test_iwdg_key_values_are_distinct);
    RUN_TEST(test_wwdg_register_block_size);
    RUN_TEST(test_exti_register_block_size);
    RUN_TEST(test_exti_line_numbers_are_distinct_and_above_gpio_range);
    RUN_TEST(test_syscfg_register_block_size);
    RUN_TEST(test_syscfg_exticr_port_values_are_distinct_and_in_range);
    return UNITY_END();
}
